# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recipients', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=250)),
                ('email_body', models.TextField(blank=True)),
                ('email_reply_to', models.EmailField(blank=True, max_length=254)),
                ('post_endpoint', models.URLField(blank=True)),
                ('default_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Distributor')),
            ],
        ),
    ]
