# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_auto_20160511_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='default_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
