# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('leads', '0001_initial'),
        ('automations', '0003_auto_20160511_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailAutomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invocation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipients', models.TextField()),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('label', models.CharField(max_length=150)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostAutomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invocation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('endpoint', models.URLField()),
                ('lead_data', models.TextField()),
                ('custom_data', models.TextField()),
                ('label', models.CharField(max_length=150)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Distributor')),
            ],
        ),
        migrations.RemoveField(
            model_name='automation',
            name='distributor',
        ),
        migrations.DeleteModel(
            name='Automation',
        ),
        migrations.AddField(
            model_name='postaction',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automations.PostAutomation'),
        ),
        migrations.AddField(
            model_name='postaction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='emailaction',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automations.EmailAutomation'),
        ),
        migrations.AddField(
            model_name='emailaction',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
        migrations.AlterUniqueTogether(
            name='postaction',
            unique_together=set([('automation', 'lead')]),
        ),
        migrations.AlterUniqueTogether(
            name='emailaction',
            unique_together=set([('automation', 'lead')]),
        ),
    ]
