# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='contact_number',
        ),
    ]
