# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_auto_20160629_1551'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='invoked_email_automations',
            field=models.ManyToManyField(blank=True, to='automations.EmailAutomation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='invoked_post_automations',
            field=models.ManyToManyField(blank=True, to='automations.PostAutomation'),
        ),
    ]
