# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20160629_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_on']},
        ),
    ]
